Add redirect path check and fix redirect path

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -6,6 +6,24 @@ on:
       - master # Here source code branch is `master`, it could be other branch
 
 jobs:
+  redirect_path_check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Check redirect path
+        run: |
+          for file in $(find ./_posts -name "*.md"); do
+            oldIfs=$IFS
+            IFS=$'\n'
+            for url in $(cat ${file} | head -n 10 | sed -n '/---/,/---/p' | sed -n '/redirect_from:/,$p' | grep ' -'); do
+                if [[ "${url}" != */ ]]; then
+                    echo "invalid redirect url: '${url}' in '${file}'"
+                    exit 1
+                fi
+            done
+            IFS=$oldIfs
+          done
+
   image_cors_check:
     runs-on: ubuntu-latest
     steps:
@@ -17,6 +35,7 @@ jobs:
           white_list: ${{ env.WHITE_LIST }}
 
   autogen_og_image:
+    needs: [redirect_path_check]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
